# configuration version 2
Vagrant.configure("2") do |config|
  servers=[
    {
      :hostname => "ktashbaeS",
      :box => "ubuntu/trusty64",
      :network => "private_network",
      :ip => "192.168.56.110",
      :provider => "virtualbox",
      :synced_folder_src => ".",
      :synced_folder_dst => "/vagrant",
      :memory => 512,
      :cpu => 1,
      :user_terminal => "shell",
      :user_data => "/scripts/install_controller.sh"
    },
    {
      :hostname => "ktashbaeSW",
      :box => "ubuntu/trusty64",
      :network => "private_network",
      :ip => "192.168.56.111",
      :provider => "virtualbox",
      :synced_folder_src => ".",
      :synced_folder_dst => "/vagrant",
      :memory => 512,
      :cpu => 1,
      :user_terminal => "shell",
      :user_data => "/scripts/install_agent.sh"
    }
  ]

  servers.each do |machine|
    # loop over each server config and define vm props
    config.vm.define machine[:hostname] do |node|
      node.vm.box = machine[:box]
      node.vm.hostname = machine[:hostname]
      node.vm.network machine[:network], ip: machine[:ip]
      node.vm.synced_folder machine[:synced_folder_src], machine[:synced_folder_dst]
      node.vm.provider machine[:provider] do |v|
        v.memory = machine[:memory]
        v.cpus = machine[:cpu]
      end
      node.vm.provision machine[:user_terminal], path: machine[:user_data]
    end
  end
end
